//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsRepair
{
    using System;
    using System.Collections.Generic;
    
    public partial class DamageBas
    {
        public int Id { get; set; }
        public string damage_type { get; set; }
        public string damage_place { get; set; }
        public string repair_type { get; set; }
    }
}
